- name: Directories are created
  file:
    path: "{{ item.dir }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items: "{{ configs }}"

- name: Container is running
  docker:
    name: jenkins
    image: jenkins
    ports: "{{ jenkins_port }}:8080"
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  register: container_result

- pause: seconds=60
  when: container_result|changed

- name: Configurations are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dir }}/{{ item.file }}"
    mode: "{{ item.mode }}"
  with_items: "{{ configs }}"
  register: configs_result

- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ facter_ipaddress_eth1 }}:{{ jenkins_port }}/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: "{{ plugins }}"
  register: plugins_result

- wait_for:
    path: /data/jenkins/plugins/{{ item }}
  with_items: "{{ plugins }}"

# Workaround to fix the bug in restarting containers from Ansible 2

- name: Container is stopped
  docker:
    name: jenkins
    image: jenkins
    state: stopped
  when: configs_result|changed or plugins_result|changed

- name: Container is running
  docker:
    name: jenkins
    image: jenkins
    ports: "{{ jenkins_port }}:8080"
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  when: configs_result|changed or plugins_result|changed

- pause: seconds=30
  when: configs_result|changed or plugins_result|changed

- name: Job directories are present
  file:
    path: "{{ home }}/jobs/{{ item }}"
    state: directory
    mode: 0777
  with_items: "{{ jobs }}"

- name: Jobs are present
  template:
    src: "{{ item }}-config.xml"
    dest: "{{ home }}/jobs/{{ item }}/config.xml"
    mode: 0777
  with_items: jobs
  register: jobs_result

- name: Jenkins is reloaded
  uri:
    url: http://{{ facter_ipaddress_eth1 }}:8080/reload
    method: POST
    status_code: 200,302
  when: jobs_result|changed
  ignore_errors: yes
