env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
    - DOCKER_HUB_USER=vfarcic

sudo: required

services:
  - docker

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_fdd0765d255b_key -iv $encrypted_fdd0765d255b_iv -in proxy-key.enc -out proxy-key -d; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then chmod 600 proxy-key; fi'

script:
  - set -e
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -v go:/go golang:1.6 bash -c "go get -d -v -t && go test --cover ./... --run UnitTest && go build -v -o docker-flow-proxy"
  - docker build -t vfarcic/docker-flow-proxy .
  - docker tag vfarcic/docker-flow-proxy vfarcic/docker-flow-proxy:beta
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy:beta; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST_IP=$(ifconfig eth0 | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | grep -Eo "([0-9]*\.){3}[0-9]*" | grep -v "127.0.0.1") docker-compose -f docker-compose-test.yml run --rm staging-swarm; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag vfarcic/docker-flow-proxy vfarcic/docker-flow-proxy:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ssh -o "StrictHostKeyChecking no" -i proxy-key root@${SWARM_MANAGER_1_PUBLIC_IP} docker service update --image vfarcic/docker-flow-proxy:${VERSION} proxy_proxy; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker-compose -f docker-compose-test.yml run --rm docs; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t vfarcic/docker-flow-proxy-docs -f Dockerfile.docs .; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag vfarcic/docker-flow-proxy-docs vfarcic/docker-flow-proxy-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy-docs; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ssh -o "StrictHostKeyChecking no" -i proxy-key root@${SWARM_MANAGER_1_PUBLIC_IP} docker service update --image vfarcic/docker-flow-proxy-docs:${VERSION} proxy_docs; fi'

branches:
  only:
    - master
